config/routes.rb
Rails.application.routes.draw do
   root :to => 'gadgets#index', :as => 'home'
   resources :gadgets
  
  get 'gadgets/index'

  get 'gadgets/show'

  get 'gadgets/edit'

  get 'gadgets/create'

  get 'gadgets/update'
  

  match "/gadgets/search_result", :via => [:get, :post]
  get 'gadgets/search_result'
  get 'gadgets/original'
  devise_for :users
  resources :users

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
	has_many :gadget_attachments
	accepts_nested_attributes_for :gadget_attachments

	
	def self.search(query)
       where("name like ?", "%#{query}%")
    end
end

app/models/gadget_attachment.rb
class GadgetAttachment < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
	belongs_to :gadget
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates_uniqueness_of :email, :case_sensitive => false, :allow_blank => true, :if => :email_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/gadget_attachments_controller.rb
class GadgetAttachmentsController < ApplicationController
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  
before_action :authenticate_user!
  before_action :set_gadget, only: [:show, :edit, :update, :destroy]

  def index
   # if params[:search]
  #   @gadgets = Gadget.search(params[:search]).order("created_at DESC")
  # else
    @gadgets = Gadget.all
  #end
  end
  def search_result
    if params[:search]
       @mygadgets = Gadget.search(params[:search]).order("created_at DESC")
    
    else
      flash[:notice] = "Nothing found. Do a search again"
    end
  end
  
  def original
    @gadget_attachments = @gadget.gadget_attachments.find(params[:id])
  end
  
  def show
     @gadget_attachments = @gadget.gadget_attachments.all
  end

  def new
    @gadget = Gadget.new

    @gadget_attachment = @gadget.gadget_attachments.build
  end

  def edit
  end

  def create
    @gadget = Gadget.new(gadget_params)
    if @gadget.save

        params[:gadget_attachments]['avatar'].each do |a|
           @gadget_attachment = @gadget.gadget_attachments.create!(:avatar => a, :gadget_id => @gadget.id)
      end
      flash[:notice] = "Successfully saved your gadget data"
    else
      flash[:notice] = "Cant create your gadgets"
      render 'new'
    end
    redirect_to @gadget
  end

  def update
     if @gadget.update(gadget_params)
      flash[:notice] = "Successfully updated"
    else
      render 'edit'
    end
    redirect_to @gadget
     
  end
  def destroy
    if @gadget.destroy
      flash[:notice] = "Deleted Successfully!"
      redirect_to @gadget
    else
      flash[:notice] = "Can't be deleted"
    end
  end

  private
   
    def set_gadget
      @gadget = Gadget.find(params[:id])
    end

   
    def gadget_params

      params.require(:gadget).permit(:name, :description, :price, gadget_attachments_attributes: [:id, :gadget_id, :avatar])

      params.require(:gadget).permit(:name, :description, :image, :price)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gadget_attachments_helper.rb
module GadgetAttachmentsHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/views/gadgets/_form.html.erb
<%= form_for(@gadget, :html => { :multipart => true }) do |f| %>



  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>

    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>
  
  <%= f.fields_for :gadget_attachments do |p| %>
  <p>
    <%= p.label :avatar %>
    <%= p.file_field :avatar, :multiple => true, name: "gadget_attachments[avatar][]" %>
  </p>
  <% end %>

    

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gadgets/_search.html.erb
<%= form_tag(:controller => 'gadgets', :action => 'search_result', :method => "get", id: "search-form") do %>
   <%= text_field_tag :search, params[:search], placeholder: "Search gadget" %>
   <%= submit_tag "Search", :name => nil ,:class => "btn-small" %>
 <% end %>

app/views/gadgets/create.html.erb
<h2>Gadgets created </h2>>

app/views/gadgets/edit.html.erb
<h1>Editing gadget</h1>

<%= render 'form' %>

<%= link_to 'Show', @gadget %> |
<%= link_to 'Back', gadgets_path %>

app/views/gadgets/index.html.erb
<h1>My gadgets</h1>

<div class="row">
<% @gadgets.each do |gadget| %>
  
    
      <div class="span3">

      
        <h4><%= link_to gadget.name, gadget %></h4>
        
      </div>
    <% end %>
 

<div class="pull-right">
<%= link_to 'New Gadget', new_gadget_path, :class =>'btn btn-primary' %>
</div>
</div>

app/views/gadgets/new.html.erb
<h1>New gadget</h1>

<%= render 'form' %>

<%#= link_to 'Back', gadgets_path %>

app/views/gadgets/original.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gadget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gadget.description %>
</p>

<p>

  <strong>Price:</strong>
  <%= @gadget.price %>
</p>

<p>
<ul class="list-view" style="list-style:none;">
<% @gadget_attachments.each do |p| %>

<li>  <%= image_tag p.avatar_url %> </li>
<% end %>
</ul>
</p>

app/views/gadgets/search.html.erb
<ul>
    <% @mygadget.each do |gadget| %>
  <li><%= link_to gadget.name, 
    :action => 'show', :id => gadget.id  %></li>
  <% end %>
  </ul>

app/views/gadgets/search_result.html.erb
<ul class="search_result" style="list-style:none;">
<% @mygadgets.each do |g| %>
<li><%= link_to g.name, g %></li>
<% end %>
</ul>

app/views/gadgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gadget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gadget.description %>
</p>

<p>

  <strong>Price:</strong>
  <%= @gadget.price %>
</p>
 <ul class="row">
<% @gadget_attachments.each do |p| %>
<li class="">
          <%= image_tag p.avatar_url(:thumb) %>    
            </li>

<% end %>
</ul>


   <p>
      <%= link_to 'Edit', edit_gadget_path(@gadget) %> |
      <%= link_to 'Destroy', @gadget, confirm: 'Are you sure?', method: :destroy %> |
      <%#= link_to 'Home', gadgets_path %>
    </p>
<%#= link_to 'Original Images', {:controller => 'gadgets', :action => 'original', :id => "#{@gadget.id }" } %>

app/views/gadgets/update.html.erb
<h1>Gadgets#update</h1>
<p>Find me in app/views/gadgets/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mygadget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-tlourbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MY Gadgets</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/gadgets">Gadgets</a></li>
      </ul>
      <p class="navbar-text pull-right">
	<% if user_signed_in? %>
	   <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
    </p>
    <div id="search pull-right">
    <%= render :partial => 'gadgets/search' if user_signed_in? %>
  </div>
    </div>
  </div>
</nav>

<div class="container">
	<%= yield %>

<footer class="footer">
  <small>
    <a href="#">Gadgets</a>
    by sukanta
  </small>
  </footer>
</html>
</div>


</body>